### ISSUE TITLE
How to set an environment variable?

### ISSUE THREAD

**Issue by shruuub** [libreddit/libreddit-instances#38]
Hi,
so for adding my i2p instance, I wanted to set the env var like I usually do, but it simply ignored setting it via `I2P_HTTP_PROXY="127.0.0.1:4444"`. As there is very little documentation on that, I thought I'd ask here. Have confirmed that the proxy is in fact running.
Thanks.

**Comment by Daniel-Valentine** [comment]
Likely a bug in how I2P is handled in the script. I'll look into this.

**Comment by shruuub** [comment]
> What is the URL to your instance?

I'd suppose you mean the i2p one, that is http://wilr7fk4bx3lnubdhxgwxg37oubmkyiqkamgfoivrz5ldtjwyitq.b32.i2p/ .

> In addition, can you show me your commands on the shell?

I'm not 100% sure as I can't check right now, but it should just be `I2P_HTTP_PROXY="127.0.0.1:4444"` and after pressing enter `generate-instances-json.sh -i ./instances.txt -o ./instances.json`

**Comment by Daniel-Valentine** [comment]
Sorry it took me a while to get to this.

You need to export the variable so that it gets added to the `generate-instances-json.sh` process. You can do this in one of two ways:

1. `I2P_HTTP_PROXY=127.0.0.1:4444 generate-instances-json.sh -i ./instances.txt -o ./instances.json`
2. `export I2P_HTTP_PROXY=127.0.0.1:4444` and then `generate-instances-json.sh -i ./instances.txt -o ./instances.json`

Let me know if you still have issues.

**Comment by shruuub** [comment]
> Sorry it took me a while to get to this.

No problem, you arent even getting paid or anything and az least you are responding! :)

But yes, both methods work perfectly, thanks a lot!
